config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  
  
  root 'static_pages#root'
  
  
  namespace :api, :defaults => {:format => :json} do

    resources :users, :only => [:show, :index, :destroy] do
      member do
        get :following, :followers
        get :likes
        get :posts
      end
    end

    post 'relationships/:id/togglefollow', to: 'relationships#toggle_follow'
    post 'posts/:id/togglelike', to: 'posts#toggle_like'
    
    resources :recipients, only: [:index]

    resources :likes, only: [:index, :show, :create]
    
    resources  :posts, only: [:create, :destroy, :show, :index] do
      resources :likes, only: [:create, :destroy]
    end
    resources :relationships, only: [:create, :destroy] 

    resources :messages, only: [:create, :destroy, :index] do
      resources :likes, only: [:create, :destroy]
    end

  end

####################################
  resources :users, :only => [:show, :index, :destroy] do
    member do
      get :following, :followers
    end
  end

  resources :links
  resources  :posts, only: [:create, :destroy, :new]
  resources :relationships,       only: [:create, :destroy]

  resources :messages, only: [:create, :destroy, :index]

end

app/models/link.rb
class Link < ActiveRecord::Base
	belongs_to :owner, :class_name => "User", :foreign_key => :user_id

	 after_create :update_from_embedly
  
  validates :intro, :presence => true
  validates :content, :presence => true, :format => URI::regexp(%w(http https))
  

  scope :recent, -> { order("updated_at DESC")}

  def editable_by?(user)
    user && user == owner
  end

  def hit
    Page.increment_counter(:count_click, self.id)
  end

  def title_for_preview
    if title.blank?
      description
    else
      title
    end
  end

  def title_for_preview
    if title.blank?
      description
    else
      title
    end
  end
  
  def update_from_embedly
 
    link = self
 
    urls = [content]

    embedly_api = Embedly::API.new(:key => Setting.embedly_key)
    embedly_objs = embedly_api.oembed(:urls => urls)
    embedly_obj = embedly_objs[0]
 
    response_data = embedly_obj.marshal_dump
 
    link.favicon_url       =  response_data[:favicon_url]
    link.title             =  response_data[:title]
    link.author_name       =  response_data[:author_name]
    link.author_url        =  response_data[:author_url]
    link.provider_name     =  response_data[:provider_name]
    link.provider_url      =  response_data[:provider_url]
    link.description       =  response_data[:description]
    link.thumbnail_url     =  response_data[:thumbnail_url]
    link.thumbnail_width   =  response_data[:thumbnail_width]
    link.thumbnail_height  =  response_data[:thumbnail_height]
    link.html              =  response_data[:html]
    link.width             =  response_data[:width]
    link.height            =  response_data[:height]
 
    link.save
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

	before_action :authenticate_user!

	def index
		@links = Link.all
	end

	def new
		@link = Link.new
	end

	def show
		@link = Link.find(params[:id])
	end

	def create
		@link = current_user.links.build(link_params)

		if @link.save
			redirect_to links_path, :notice => "I like"
		else
			render :new
		end
	end

	private

	def link_params
		params.require(:link).permit(:content, :intro, :title, :thumbnail_url, :description)
	end

end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/index.html.erb
<div id="pages-index">
  <div class="hero-unit">
    <h1 class="text-center">Ruby on Rails<br>Exchange Center</h1>
    <p class="text-center"><span class="word-block">Ruby on Rails</span></p>
  </div>
</div>

<div id="pages">
<% @links.each do |link| %>
  <%= div_for link do %>
  <div class="span6 mg-auto page_index_titles">
    <h4 class="float-clear"> <%= link.owner.name %> ：&nbsp;<%= link.intro %></h4>
    <div class="span6">
      <div class="thumb">
        <div class="items">
          <% if link.thumbnail_url.nil? %>
            <ul class="images"><li><%= image_tag("no_img.jpg") %></li></ul>
          <% else %>
            <ul class="images"><li><img src="<%= link.thumbnail_url %>"></li></ul>
          <% end %>
        </div>
      </div>
      <div class="attributes">
        <%= link.html.html_safe %>
        <%= link_to(link.title, link.content, :class => "index-title") %>
        <% if link.description.nil? %>
          <p class="index-p muted">遮了國防布，完全沒有內容 XD
          <br>該網站無法自動抓取連結資訊
          <br>如果您是作者，請點選下面按鈕幫忙調整 
          <%= link_to("Here", edit_link_link_path(link) , :class => "btn btn-danger btn-mini" )%></p>
        <% else %>
          <p class="index-p muted"><%= link.description %></p>
        <% end %>
      </div>
    </div>
  </div>
  
  <% end %>
<% end %>
</div>

app/views/links/new.html.erb
<div id="page_input" class="float-clear mg-auto">
  <h1 class="text-center">新增文章</h1>
  <div class="form-area">
    
    <%= form_for @link do |f| %>
      <%= f.text_field :content, placeholder: "Submit a URL", class: "form-control", id: "url" %><br>
      
      <div class="new_page_form">
        <div class="selector-wrapper"></div>
      </div>


        <%= f.text_area :intro, placeholder: "Why is this song the shiznit?" %>
        
        <%= f.submit "Submit", class: "full-width" %>
      <% end %>
  </div>
</div>

<%= content_for :javascripts do %>
  <%= javascript_tag do %>
    // Set up preview.
      
    $('#url').preview({key: '<%= Setting.embedly_key %>'})

    // On submit add hidden inputs to the form.
    $('form').on('submit', function(){
      $(this).addInputs($('#url').data('preview'));
      return true;
    });
  <% end %>
<% end %>

app/views/links/show.html.erb
<div class="button_group span10 mg-auto">
  <div class="button_grup pull-right">
    <% if current_user && @link.editable_by?(current_user) %>
      <%= link_to("Edit", edit_link_path(@link) , :class => "btn btn-info btn-large" )%>
    <% end %>
    <%= link_to("Back", links_path , :class => "btn btn-large btn-success" )%>
    </div>
</div>

<% if @link.title.blank? %>
  <h1 class="page_head_title text-center">沒有標題</h1>
<% else %>
  <h1 class="page_head_title text-center"><%= @link.title %></h1>
<% end %>

<p class="page_head_text text-center"><%= @link.intro %></p>


<!-- page的部分   -->
    <div class="span6 mg-auto page_index_titles">
      <h4 class="float-clear"> 
        <%= @link.owner.name %> ：&nbsp;<%= @link.intro %>
      </h4>
      <div class="span6">

        <div class="thumb">
          <div class="items">
            <% if @link.thumbnail_url.nil? %>
              <ul class="images">
                <li><%= image_tag("no_img.jpg") %></li>
              </ul>
            <% else %>
              <ul class="images">
                <li><img src="<%= @link.thumbnail_url %>"></li>
              </ul>
            <% end %>
          </div>
        </div>

        <div class="attributes">
          <%= link_to(@link.title, @link.content, :class => "index-title") %>
          <% if @link.description.nil? %>
            <p class="index-p muted">遮了國防布，完全沒有內容 XD
              <br>該網站無法自動抓取連結資訊
              <br>如果您是作者，請點選下面按鈕幫忙調整 
              <%= link_to("Here", edit_link_link_path(@link) , 
                          :class => "btn btn-danger btn-mini" )%>
            </p>
          <% else %>
            <p class="index-p muted">
              <%= link.description %>
            </p>
          <% end %>
        </div>

      </div>
    </div>

<div class="span6 mg-auto"><hr></div>

<div id="show_page_messenge" class="span6 mg-auto">
  <h2 class="text-center page_show_titles">推薦原因</h2>
  <p class="page_text page_index_titles"><%= simple_format(@link.messenge) %></p>
</div>

<div class="span6 mg-auto"><hr></div>
<!-- end - page的部分   -->